### ISSUE TITLE
Communication between the android app and back-end - request for the details of a specific (single) study

### ISSUE THREAD

**Issue by everKalle** [everKalle/ExperienceSamplingApplication#31]
25h

should later be split into two parts - android app making the request and back-end handling the request and returning the data

Android app functional requirement 2
Back-end functional requirement 10
[Android app use case](https://github.com/everKalle/ExperienceSamplingApplication/wiki/Android-rakenduse-use-case'id#use-case-uc-a-2-uuringuga-liitumine)
[Back-end use case](https://github.com/everKalle/ExperienceSamplingApplication/wiki/Back-end'i-%28veebirakenduse%29-use-case'id#use-case-uc-b-12-kindla-uuringu-andmete-tagastamine)

Will be done once #60 and #61 are completed

**Comment by madiskar** [comment]
Query structure was changed, this issue is now obsolete.
